http:
  port: 3000

apiEndpoints:
  users:
    path: /users
    methods: GET, POST, PUT, DELETE

  userById:
    path: /users/:id
    methods: GET, PUT, DELETE

  posts:
    path: /posts
    methods: GET, POST

  postById:
    path: /posts/:id
    methods: GET, PUT, DELETE

  postsByUser:
    path: /posts/user/:userId
    methods: GET

serviceEndpoints:
  user-service:
    url: http://user-service:3001
  post-service:
    url: http://post-service:3002

policies:
  - proxy

pipelines:
  users-pipeline:
    apiEndpoints:
      - users
      - userById
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true
              strip_path: false

  posts-pipeline:
    apiEndpoints:
      - posts
      - postById
      - postsByUser
    policies:
      - proxy:
          - action:
              serviceEndpoint: post-service
              changeOrigin: true
              strip_path: false
